from __future__ import annotations

import argparse
import collections
import json
import math
import statistics as st
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EP = REPO / "results" / "eval_protocol"

OURS = "decod550"
FINETUNED = ["sft", "rl650", "judge550"]
REFERENCE = ["base", "teacher72b"]
RIVALS = FINETUNED + REFERENCE
LABEL = {"base": "base (untuned init)", "sft": "sft", "rl650": "rl650",
         "judge550": "judge550", "teacher72b": "teacher72b"}


def mcq_by_series(tag: str, bench: str, metric: str) -> dict[str, float]:
    g: dict[str, list[float]] = collections.defaultdict(list)
    with open(EP / f"{bench}_mcq" / f"{tag}.jsonl", encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            if r["metric"] == metric:
                g[r["series_uid"]].append(r["correct"])
    return {k: st.mean(v) for k, v in g.items()}


def bedtime_nli_by_series(tag: str, thr: float = 0.5) -> dict[str, float]:
    g: dict[str, list[float]] = collections.defaultdict(list)
    with open(EP / "bedtime" / tag / "generation_deployed.jsonl", encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            g[r["series_uid"]].append(1.0 if r["p_gen_entails_gt"] >= thr else 0.0)
    return {k: st.mean(v) for k, v in g.items()}


def cats_nli_by_series(tag: str) -> dict[str, float]:
    g: dict[str, float] = {}
    with open(EP / "cats_gengt" / "nli_cats" / f"{tag}_qualitative.jsonl", encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            g[r["series_uid"]] = 1.0 if r["p_gen_entails_gt"] >= 0.5 else 0.0
    return g


COLUMNS = [
    ("BT gen->gt", bedtime_nli_by_series),
    ("BT cap->ser", lambda t: mcq_by_series(t, "bedtime", "A")),
    ("BT ser->cap", lambda t: mcq_by_series(t, "bedtime", "B")),
    ("CaTS gen->gt", cats_nli_by_series),
    ("CaTS cap->ser", lambda t: mcq_by_series(t, "cats", "A")),
    ("CaTS ser->cap", lambda t: mcq_by_series(t, "cats", "B")),
]


def norm_sf(z: float) -> float:
    return 0.5 * math.erfc(abs(z) / math.sqrt(2))


def paired(a: dict[str, float], b: dict[str, float]) -> tuple[float, float, int]:
    keys = sorted(set(a) & set(b))
    d = [a[k] - b[k] for k in keys]
    n = len(d)
    m, sd = st.mean(d), st.stdev(d)
    if sd == 0:
        return m, (0.0 if m else 1.0), n
    z = m / (sd / math.sqrt(n))
    return m, 2 * norm_sf(z), n


def two_proportion(p1: float, n1: int, p2: float, n2: int) -> float:
    p = (p1 * n1 + p2 * n2) / (n1 + n2)
    se = math.sqrt(p * (1 - p) * (1 / n1 + 1 / n2))
    return 2 * norm_sf((p1 - p2) / se) if se else 1.0


def holm(items: list[tuple[str, float]]) -> dict[str, float]:
    order = sorted(items, key=lambda t: t[1])
    m, out, running = len(order), {}, 0.0
    for i, (name, p) in enumerate(order):
        running = max(running, (m - i) * p)
        out[name] = min(1.0, running)
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=EP / "criteria12_significance.md")
    args = ap.parse_args()

    cache: dict[tuple[str, str], dict[str, float]] = {}

    def col(name: str, tag: str) -> dict[str, float]:
        if (name, tag) not in cache:
            cache[(name, tag)] = dict(COLUMNS)[name](tag)
        return cache[(name, tag)]

    rows = []
    families: dict[str, list[tuple[str, float]]] = {"fine-tuned": [], "reference": []}
    for name, _ in COLUMNS:
        ours = col(name, OURS)
        for r in RIVALS:
            gap, p, n = paired(ours, col(name, r))
            mo = st.mean(ours.values())
            mr = st.mean(col(name, r).values())
            fam = "fine-tuned" if r in FINETUNED else "reference"
            rows.append([name, r, mo, mr, gap, n, p, fam])
            families[fam].append((f"{name}|{r}", p))

    adj = {}
    for fam, items in families.items():
        adj.update(holm(items))

    def leads(fam: str) -> tuple[int, int, list[str]]:
        cells = [row for row in rows if row[7] == fam]
        behind = [f"{row[0]} vs {row[1]}" for row in cells if row[4] <= 0]
        return len(cells) - len(behind), len(cells), behind

    out = ["# Criteria 1 and 2: are the gaps significant?", "",
           f"Generated by `python -m ts_bedtime.criteria12_sig`. {OURS} against each other arm, "
           f"one paired test per (column, arm), Holm-corrected within two families: the three "
           f"captioners fine-tuned from the same initialisation ({', '.join(FINETUNED)}; "
           f"{len(families['fine-tuned'])} comparisons) and the two reference models "
           f"({', '.join(REFERENCE)}; {len(families['reference'])} comparisons).", "",
           "Rotations are averaged within a series before pairing, and BEDTime gen->gt is folded "
           "to one entailment rate per series before pairing, so n counts series, not questions "
           "or reference pairs. See the module docstring for what the pairing does and does not "
           "cover.", "",
           "| metric | rival | ours | rival | gap | n | p | p (Holm, within family) | family |",
           "|---|---|---|---|---|---|---|---|---|"]
    for name, r, mo, mr, gap, n, p, fam in rows:
        key = f"{name}|{r}"
        out.append(f"| {name} | `{r}` | {mo:.3f} | {mr:.3f} | {gap:+.3f} | {n} | "
                   f"{p:.2e} | {adj[key]:.2e} | {fam} |")
    out.append("")
    for fam in ("fine-tuned", "reference"):
        won, total, behind = leads(fam)
        worst = max(adj[k] for k, _ in families[fam])
        sig = sum(adj[k] < 0.05 for k, _ in families[fam])
        line = (f"**{fam} family**: {OURS} has the higher mean in {won} of {total} cells "
                f"({sig} of {total} significant at Holm-adjusted p < 0.05; largest adjusted "
                f"p = {worst:.2e}).")
        if behind:
            line += " Cells where it is behind: " + ", ".join(behind) + "."
        out.append(line)
        out.append("")
    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {args.out}")
    for fam in ("fine-tuned", "reference"):
        won, total, behind = leads(fam)
        print(f"{fam}: leads {won}/{total}, largest Holm p = {max(adj[k] for k, _ in families[fam]):.2e}"
              + (f", behind in {behind}" if behind else ""))


if __name__ == "__main__":
    main()
