from __future__ import annotations

import argparse
import collections
import json
import statistics as st
from pathlib import Path

import numpy as np

from ts_bedtime.criteria12_sig import holm, paired
from ts_eval.stats import boot_mean, boot_paired_delta

REPO = Path(__file__).resolve().parents[1]
EP = REPO / "results" / "eval_protocol"
XV = EP / "xverifier"

ARMS = ["base", "sft", "rl650", "judge550", "decod550", "teacher72b",
        "qwen3vl-8b", "internvl3-14b", "phi35-mini", "qwen25-7b", "qwen25-14b", "chatts-14b",
        "neg6", "negrand", "rm3b", "rm7b", "neg8"]
PUBLISHED_READER = "qwen25-14b"
PARITY_TOL = 0.01


def by_series(path: Path, metric: str) -> dict[str, float]:
    g: dict[str, list[float]] = collections.defaultdict(list)
    with open(path, encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            if r["metric"] == metric:
                g[r["series_uid"]].append(r["correct"])
    return {k: st.mean(v) for k, v in g.items()}


def load_json(path: Path) -> dict | None:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def ci_str(vals, n_boot: int, seed: int) -> str:
    m, lo, hi = boot_mean(list(vals), n_boot=n_boot, seed=seed)
    return f"{m:.3f} [{lo:.3f}, {hi:.3f}]"


def delta_str(a: dict[str, float], b: dict[str, float], n_boot: int, seed: int
              ) -> tuple[str, float, int]:
    keys = sorted(set(a) & set(b))
    if not keys:
        return "n/a", 1.0, 0
    d, lo, hi = boot_paired_delta([a[k] for k in keys], [b[k] for k in keys],
                                  n_boot=n_boot, seed=seed)
    _, p, n = paired({k: a[k] for k in keys}, {k: b[k] for k in keys})
    return f"{d:+.3f} [{lo:+.3f}, {hi:+.3f}]", p, n


def spearman(x, y) -> float:
    from scipy.stats import spearmanr
    return float(spearmanr(x, y).correlation)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bench", required=True, choices=("bedtime", "cats"))
    ap.add_argument("--root", type=Path, default=None,
                    help="defaults to results/eval_protocol/xverifier/<bench>")
    ap.add_argument("--readers", default=None,
                    help="comma-separated reader tags; default: every subdir not ending "
                         "in _smoke, published reader first")
    ap.add_argument("--arms", default=",".join(ARMS))
    ap.add_argument("--published", type=Path, default=None,
                    help="defaults to results/eval_protocol/<bench>_mcq")
    ap.add_argument("--n-boot", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    root = args.root or XV / args.bench
    published = args.published or EP / f"{args.bench}_mcq"
    arms = [a for a in args.arms.split(",") if a]
    if args.readers:
        readers = [r for r in args.readers.split(",") if r]
    else:
        readers = sorted(p.name for p in root.iterdir()
                         if p.is_dir() and not p.name.endswith("_smoke"))
        if PUBLISHED_READER in readers:
            readers.remove(PUBLISHED_READER)
            readers.insert(0, PUBLISHED_READER)
    out_path = args.out or root / "report.md"
    nb, seed = args.n_boot, args.seed

    L: list[str] = []
    L += [f"# Cross-reader identification report: {args.bench}", "",
          f"Generated by `python -m ts_bedtime.xverifier_report --bench {args.bench}`. "
          f"Readers: {', '.join('`' + r + '`' for r in readers)}. Rotations are averaged "
          f"within a series before anything is compared; CIs are percentile bootstraps over "
          f"series ({nb} resamples, seed {seed}); p-values are paired z-tests over series, "
          f"Holm-corrected within each family.", ""]

    per: dict[tuple[str, str, str], dict[str, float]] = {}
    missing: list[str] = []
    for r in readers:
        for a in arms:
            jl = root / r / f"{a}.jsonl"
            if not jl.exists():
                missing.append(f"{r}/{a}")
                continue
            for m in ("A", "B"):
                per[(r, a, m)] = by_series(jl, m)

    L += ["## 1. Arms x readers (full rotation, real captions)", "",
          "| arm | " + " | ".join(f"{r} c->s | {r} s->c" for r in readers) + " |",
          "|---|" + "---|---|" * len(readers)]
    for a in arms:
        cells = []
        for r in readers:
            for m in ("A", "B"):
                v = per.get((r, a, m))
                cells.append(ci_str(v.values(), nb, seed) if v else "—")
        L.append(f"| `{a}` | " + " | ".join(cells) + " |")
    L.append("")
    L += ["Arm ranking per reader (best first):", ""]
    for r in readers:
        for m, name in (("A", "c->s"), ("B", "s->c")):
            avail = [(st.mean(per[(r, a, m)].values()), a) for a in arms if (r, a, m) in per]
            if avail:
                L.append(f"- `{r}` {name}: " + " > ".join(
                    f"{a} ({v:.3f})" for v, a in sorted(avail, reverse=True)))
    L.append("")

    if PUBLISHED_READER in readers and published.exists():
        worst, checked = 0.0, 0
        for a in arms:
            pub = load_json(published / f"{a}.json")
            new = load_json(root / PUBLISHED_READER / f"{a}.json")
            if pub is None or new is None:
                continue
            for m in ("A", "B"):
                if m in pub and m in new:
                    worst = max(worst, abs(pub[m]["accuracy"] - new[m]["accuracy"]))
                    checked += 1
        verdict = "reproduces" if worst <= PARITY_TOL else "DOES NOT reproduce"
        L += [f"Parity: the `{PUBLISHED_READER}` re-run {verdict} `{published.name}/` "
              f"(largest |delta| over {checked} cells = {worst:.4f}; tolerance {PARITY_TOL}, the "
              f"re-scoring noise of vLLM greedy decoding across GPUs/batches is about 0.005). "
              f"Per cell (published -> re-run): " + "; ".join(
                  f"{a} {m} {load_json(published / f'{a}.json')[m]['accuracy']:.3f}->"
                  f"{load_json(root / PUBLISHED_READER / f'{a}.json')[m]['accuracy']:.3f}"
                  for a in arms for m in ("A", "B")
                  if load_json(published / f"{a}.json") and load_json(root / PUBLISHED_READER / f"{a}.json")
                  and m in load_json(published / f"{a}.json") and m in load_json(root / PUBLISHED_READER / f"{a}.json")) + ".", ""]

    L += ["## 2. Do the readers agree?", "",
          "Spearman rank correlation between readers: over the arm means (n = number of "
          "arms) and over per-series accuracies pooled across arms (do two readers find "
          "the same items hard).", "",
          "| pair | metric | rho (arms) | rho (series, pooled) | n series |",
          "|---|---|---|---|---|"]
    for i, r1 in enumerate(readers):
        for r2 in readers[i + 1:]:
            for m, name in (("A", "c->s"), ("B", "s->c")):
                shared_arms = [a for a in arms if (r1, a, m) in per and (r2, a, m) in per]
                if len(shared_arms) < 3:
                    continue
                x = [st.mean(per[(r1, a, m)].values()) for a in shared_arms]
                y = [st.mean(per[(r2, a, m)].values()) for a in shared_arms]
                xs, ys = [], []
                for a in shared_arms:
                    p1, p2 = per[(r1, a, m)], per[(r2, a, m)]
                    for k in sorted(set(p1) & set(p2)):
                        xs.append(p1[k])
                        ys.append(p2[k])
                L.append(f"| `{r1}` vs `{r2}` | {name} | {spearman(x, y):+.2f} "
                         f"(n={len(shared_arms)}) | {spearman(xs, ys):+.3f} | {len(xs)} |")
    L.append("")

    L += ["## 3. Controls", ""]
    L += ["### 3a. No caption (`empty`)", "",
          "Metric A with the placeholder caption: above 1/4 means the candidate set itself "
          "leaks the target. Metric B with four identical options: the position prior.", "",
          "| reader | c->s (A) [CI] | s->c (B) | A by gold position | B by gold position | unparsed |",
          "|---|---|---|---|---|---|"]
    for r in readers:
        e = load_json(root / r / "empty.json")
        if e is None:
            L.append(f"| `{r}` | — | — | — | — | — |")
            continue
        def pos(entry):
            return " ".join(f"{k}:{v:.2f}" for k, v in entry["by_gold_position"].items())
        ejl = root / r / "empty.jsonl"
        ea = ci_str(by_series(ejl, "A").values(), nb, seed) if ejl.exists() else f"{e['A']['accuracy']:.3f}"
        L.append(f"| `{r}` | {ea} (n={e['A']['n_series']}) | "
                 f"{e['B']['accuracy']:.3f} | {pos(e['A'])} | {pos(e['B'])} | "
                 f"{e['unparsed_rate']:.3%} |")
    L.append("")

    L += ["### 3b. Wrong caption (`mismatch`) vs the arm's own captions", "",
          "Each series scored with another same-group series' caption from the same arm "
          "(donor never one of the item's four candidates, except the flagged items where "
          "no such donor exists). Delta = mismatch - own, paired over series.", "",
          "| reader | arm | own c->s | mismatch c->s | delta [CI] | p (Holm) | own s->c | "
          "mismatch s->c | delta [CI] | p (Holm) | donor in candidates |",
          "|---|---|---|---|---|---|---|---|---|---|---|"]
    fam: list[tuple[str, float]] = []
    cells: dict[str, list] = {}
    for r in readers:
        for a in arms:
            jl = root / r / f"{a}_mismatch.jsonl"
            if not jl.exists() or (r, a, "A") not in per:
                continue
            js = load_json(root / r / f"{a}_mismatch.json") or {}
            row = [r, a]
            for m in ("A", "B"):
                mm = by_series(jl, m)
                own = per[(r, a, m)]
                d, p, n = delta_str(mm, own, nb, seed)
                key = f"{r}|{a}|{m}"
                fam.append((key, p))
                row += [f"{st.mean(own.values()):.3f}", f"{st.mean(mm.values()):.3f}", d, key]
            row.append(str(js.get("mismatch_donor_in_candidates", "?")))
            cells[f"{r}|{a}"] = row
    adj = holm(fam) if fam else {}
    for row in cells.values():
        r, a = row[0], row[1]
        L.append(f"| `{r}` | `{a}` | {row[2]} | {row[3]} | {row[4]} | {adj[row[5]]:.1e} | "
                 f"{row[6]} | {row[7]} | {row[8]} | {adj[row[9]]:.1e} | {row[10]} |")
    L.append("")

    L += ["### 3c. Single random position (`random`) vs full rotation", "",
          "One seeded permutation of the four options per item (same permutation for every "
          "arm and reader) against the four-rotation average. Delta = random - rotation, "
          "paired over series; a CI containing 0 means the cheap protocol agrees with the "
          "full one on this reader.", "",
          "| reader | arm | rotation c->s | random c->s | delta [CI] | p (Holm) | "
          "rotation s->c | random s->c | delta [CI] | p (Holm) | random by gold position (A) |",
          "|---|---|---|---|---|---|---|---|---|---|---|"]
    fam, cells = [], {}
    for r in readers:
        for a in arms:
            jl = root / r / f"{a}_random.jsonl"
            if not jl.exists() or (r, a, "A") not in per:
                continue
            js = load_json(root / r / f"{a}_random.json") or {}
            row = [r, a]
            for m in ("A", "B"):
                rr = by_series(jl, m)
                own = per[(r, a, m)]
                d, p, n = delta_str(rr, own, nb, seed)
                key = f"{r}|{a}|{m}"
                fam.append((key, p))
                row += [f"{st.mean(own.values()):.3f}", f"{st.mean(rr.values()):.3f}", d, key]
            bgp = js.get("A", {}).get("by_gold_position", {})
            row.append(" ".join(f"{k}:{v:.2f}" for k, v in bgp.items()))
            cells[f"{r}|{a}"] = row
    adj = holm(fam) if fam else {}
    for row in cells.values():
        r, a = row[0], row[1]
        L.append(f"| `{r}` | `{a}` | {row[2]} | {row[3]} | {row[4]} | {adj[row[5]]:.1e} | "
                 f"{row[6]} | {row[7]} | {row[8]} | {adj[row[9]]:.1e} | {row[10]} |")
    L.append("")

    masked_rows = []
    for r in readers:
        for a in arms:
            vm = root / r / f"{a}_valmask.jsonl"
            if not vm.exists() or (r, a, "A") not in per:
                continue
            nm = root / r / f"{a}_nummask.jsonl"
            stats_p = EP / "masked" / args.bench / f"summary_{a}.json"
            stats = load_json(stats_p) or {}
            own = per[(r, a, "A")]
            v = by_series(vm, "A")
            d_v, p_v, _ = delta_str(v, own, nb, seed)
            cell = [r, a, f"{st.mean(own.values()):.3f}", f"{st.mean(v.values()):.3f}", d_v]
            if nm.exists():
                n_ = by_series(nm, "A")
                d_n, p_n, _ = delta_str(n_, own, nb, seed)
                cell += [f"{st.mean(n_.values()):.3f}", d_n]
            else:
                cell += ["—", "—"]
            cell.append(f"{stats.get('density_before', float('nan')):.3f} -> "
                        f"{stats.get('density_after', float('nan')):.3f}" if stats else "—")
            cell.append(f"{stats.get('masked_frac', float('nan')):.2f}" if stats else "—")
            masked_rows.append(cell)
    if masked_rows:
        L += ["## 5. Identification with the numerals masked (metric A)", "",
              "`valmask`: the caption's y-values replaced by `<val>` by the LLM masker of the "
              "valmask reward (time references kept); `nummask`: every numeral replaced by a "
              "regex (time references lost too). What survives masking is the caption's claim "
              "about shape and position; the drop is the share of identification that rested "
              "on quoted values. Numeric density = share of whitespace tokens with a digit.", "",
              "| reader | arm | c->s as written | valmask | Δ [CI] | nummask | Δ [CI] | "
              "numeric density before -> after | share of numbers masked |",
              "|---|---|---|---|---|---|---|---|---|"]
        for c in masked_rows:
            L.append("| `" + c[0] + "` | `" + c[1] + "` | " + " | ".join(c[2:]) + " |")
        L.append("")

    L += ["## 4. Reply parsing per reader", "",
          "| reader | files | unparsed (pooled) | system role | letters single-token |",
          "|---|---|---|---|---|"]
    for r in readers:
        files = sorted((root / r).glob("*.json")) if (root / r).exists() else []
        tot_u, tot_n, sys_ok, single = 0, 0, None, None
        for f in files:
            j = load_json(f)
            if not j or "unparsed" not in j:
                continue
            n = sum(j[m]["n"] for m in ("A", "B") if m in j)
            tot_u += j["unparsed"]
            tot_n += n
            sys_ok = j.get("system_role_supported", sys_ok)
            single = j.get("letters_single_token", single)
        rate = f"{tot_u / tot_n:.3%}" if tot_n else "—"
        L.append(f"| `{r}` | {len(files)} | {rate} ({tot_u}/{tot_n}) | {sys_ok} | "
                 f"{'all' if single and all(single.values()) else single} |")
    L.append("")
    if missing:
        L += ["Missing (not yet scored): " + ", ".join(f"`{m}`" for m in missing), ""]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
