from __future__ import annotations

from pathlib import Path

from .xverifier_csv import ARM_ORDER, READER_ORDER, XV

READER_FLAGS = {
    "qwen25-14b": ("Qwen/Qwen2.5-14B-Instruct", "--max-tokens 8"),
    "llama31-8b": ("meta-llama/Llama-3.1-8B-Instruct", "--max-tokens 16"),
    "gemma3-12b": ("google/gemma-3-12b-it", "--max-tokens 16 --mm-zero"),
    "mistral-nemo-12b": ("mistralai/Mistral-Nemo-Instruct-2407", "--max-tokens 16 --max-model-len 65536"),
    "phi4-14b": ("microsoft/phi-4", "--max-tokens 512 --max-model-len 16384"),
    "glm4-9b": ("zai-org/GLM-4-9B-0414", "--max-tokens 16"),
    "qwen3-14b": ("Qwen/Qwen3-14B", "--max-tokens 16"),
    "qwen35-9b": ("Qwen/Qwen3.5-9B", "--max-tokens 16 --mm-zero"),
}
BEDTIME_ONLY_MISSING = ("rm3b", "rm7b", "neg8")
CAPS = {
    "bedtime": {a: f"results/eval_protocol/xverifier/inputs/bedtime_captions_{a}.jsonl" for a in ARM_ORDER[:6] + ["neg6", "negrand"]},
    "cats": {a: f"results/eval_protocol/cats_mcq/captions_{a}.jsonl" for a in ARM_ORDER},
}
for a in ("qwen3vl-8b", "internvl3-14b"):
    CAPS["bedtime"][a] = f"results/eval_protocol/vlm_zoo/bedtime/captions_{a}.jsonl"
    CAPS["cats"][a] = f"results/eval_protocol/vlm_zoo/cats/captions_{a}.jsonl"
for a in ("phi35-mini", "qwen25-7b", "qwen25-14b", "chatts-14b"):
    CAPS["bedtime"][a] = f"results/eval_protocol/text_zoo/bedtime/captions_{a}.jsonl"
    CAPS["cats"][a] = f"results/eval_protocol/text_zoo/cats/captions_{a}.jsonl"
SERIES = {"bedtime": "results/decodability_rl/reader_k_sweep/inputs/bedtime_series.jsonl --exclude-datasets sushi",
          "cats": "data/cats/cats_qualitative_series.jsonl --exclude-datasets \"\" --pool-negatives-across-datasets"}
SUFFIXES = ("", "_random", "_mismatch", "_mismatch_random")


def cell_state(d: Path, arm: str) -> str:
    n = sum((d / f"{arm}{s}.json").exists() for s in SUFFIXES)
    return "done" if n == 4 else ("partial" if n else "missing")


def main() -> None:
    L = ["# Identification cells: done / missing", "",
         "Generated by `python -m ts_bedtime.xverifier_status` from the JSON summaries under "
         "`results/eval_protocol/xverifier/<bench>/<reader>/`. A cell is done when its four "
         "summaries (rotation, random order, mismatch, mismatch+random) exist. `empty` is one "
         "control per (bench, reader). First-round ablation arms (rm3b, rm7b, neg8) have "
         "no BEDTime captions, so those cells do not exist by design.", "",
         "Every missing or partial cell is listed with its exact command at the end of this file. "
         "The protocol is deterministic to +-0.005 and the JSON layout is identical, so a cell can "
         "be run on any machine and dropped into place.", ""]
    missing_cmds = []
    for bench in ("bedtime", "cats"):
        arms = [a for a in ARM_ORDER if not (bench == "bedtime" and a in BEDTIME_ONLY_MISSING)]
        L += [f"## {bench}", "", "| arm | " + " | ".join(READER_ORDER) + " |", "|---|" + "---|" * len(READER_ORDER)]
        for a in arms:
            cells = []
            for r in READER_ORDER:
                d = XV / bench / r
                st = cell_state(d, a) if d.exists() else "missing"
                cells.append({"done": "✅", "partial": "◐", "missing": "—"}[st])
                if st != "done":
                    model, flags = READER_FLAGS[r]
                    missing_cmds.append(
                        f"# {bench} / {r} / {a}\npython -m ts_bedtime.mcq_metrics --arm {a} --bench {bench} "
                        f"--series {SERIES[bench]} --captions {CAPS[bench][a]} --reader {model} --reader-tag {r} "
                        f"{flags} --controls none,mismatch --order rotation,random")
            L.append(f"| `{a}` | " + " | ".join(cells) + " |")
        emp = []
        for r in READER_ORDER:
            d = XV / bench / r
            ok = (d / "empty.json").exists() and (d / "empty_random.json").exists()
            emp.append("✅" if ok else "—")
            if not ok:
                model, flags = READER_FLAGS[r]
                missing_cmds.append(
                    f"# {bench} / {r} / empty control\npython -m ts_bedtime.mcq_metrics --arm decod550 --bench {bench} "
                    f"--series {SERIES[bench]} --captions {CAPS[bench]['decod550']} --reader {model} --reader-tag {r} "
                    f"{flags} --controls empty --order rotation,random")
        L.append(f"| `empty` control | " + " | ".join(emp) + " |")
        L.append("")
    n_done = sum(1 for c in L if "✅" in c)
    L += ["## Commands for every missing or partial cell", "",
          f"{len(missing_cmds)} cells. Run from the repo root. Outputs "
          "land in `results/eval_protocol/xverifier/<bench>/<reader>/`.", "",
          "```bash", *missing_cmds, "```", ""]
    out = XV / "STATUS.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}: {len(missing_cmds)} missing/partial cells")


if __name__ == "__main__":
    main()
