from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np

from ts_downstream.datasets import load_dataset

ARMS = ["base", "decod550", "sft", "teacher72b"]
ARM_LABEL = {
    "base": "base -- Qwen2.5-VL-3B-Instruct (untuned)",
    "decod550": "**decod550 -- decodability RL (ours)**",
    "sft": "**sft -- 3B distilled from the 72B teacher**",
    "teacher72b": "teacher72b -- Qwen2.5-VL-72B-Instruct (the SFT teacher)",
}

GROUPS = [
    ("ECG5000 (classification, SFT wins)", "ucr:ECG5000", "pipeline3/ucr_ECG5000",
     {"task": "classification", "limit": 1000}),
    ("TwoPatterns (classification, RL wins)", "ucr:TwoPatterns", "pipeline3/ucr_TwoPatterns",
     {"task": "classification", "limit": 1000}),
    ("ETTh2 (forecasting, RL wins)",
     "ett:bench_data/TSF/ETT-small/ETTh2.csv:OT",
     "pipeline3_forecast/ETTh2",
     {"task": "forecasting", "lookback": 128, "horizon": 16, "max_windows": 5000}),
]


def truth_block(series: np.ndarray) -> str:
    s = np.asarray(series, dtype=float)
    d = np.abs(np.diff(s))
    return (
        f"- length {len(s)}, first value {s[0]:.2f}, last value {s[-1]:.2f}\n"
        f"- max {s.max():.2f} @ t={int(s.argmax())} · min {s.min():.2f} @ t={int(s.argmin())}\n"
        f"- mean {s.mean():.2f} · std {s.std():.2f} · largest one-step jump {d.max():.2f} "
        f"@ t={int(d.argmax())}\n"
    )


def stats_row(caps: list[str]) -> dict:
    chars = sorted(len(c) for c in caps)
    nums = sorted(len(re.findall(r"-?\d+\.?\d*", c)) for c in caps)
    openings: dict[str, int] = {}
    for c in caps:
        k = " ".join(c.split()[:8])
        openings[k] = openings.get(k, 0) + 1
    vocab = set()
    for c in caps[:300]:
        vocab.update(w.lower().strip(".,;:()") for w in c.split())
    return {
        "n": len(caps),
        "chars_med": chars[len(chars) // 2],
        "nums_med": nums[len(nums) // 2],
        "top_opening_rate": max(openings.values()) / len(caps),
        "vocab_300": len(vocab),
    }


def load_caps(root: Path, group_dir: str, arm: str) -> dict[str, str] | None:
    p = root / group_dir / arm / "captions.jsonl"
    if not p.exists():
        return None
    return {json.loads(l)["id"]: json.loads(l)["caption"] for l in open(p, encoding="utf-8")}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="results/eval_protocol/caption_examples_sft_vs_rl.md")
    ap.add_argument("--n-per-dataset", type=int, default=3)
    ap.add_argument("--root", default="results/eval_protocol")
    ap.add_argument("--seed", type=int, default=2020)
    args = ap.parse_args()
    root = Path(args.root)

    md: list[str] = [
        "# SFT vs RL: same chart, same prompt, what did each model say?\n",
        "\nEvery arm received the **identical image** (same series, same renderer) and the "
        "**byte-identical prompt**\n"
        "(`decodability_rl/rl/cap_prompt.py:TS_CAP_PROMPT`, no system message), decoded "
        "greedily.\n"
        "So any difference on this page is a difference in what the model chose to say.\n\n"
        "The \"ground truth\" block is **computed from the raw values**, not written by any "
        "model, so it can be used directly to check who is making things up.\n",
        "\nGenerated by `python -m decodability_rl.sft.make_caption_comparison`.\n",
    ]

    md.append("\n## 0. Style statistics (all captions of each dataset)\n")
    md.append("\n| dataset | arm | n | median chars | median #numbers | top-opening rate | "
              "vocabulary (first 300) |\n")
    md.append("|---|---|--:|--:|--:|--:|--:|\n")
    for title, _spec, gdir, _kw in GROUPS:
        for arm in ARMS:
            caps = load_caps(root, gdir, arm)
            if not caps:
                continue
            s = stats_row(list(caps.values()))
            md.append(f"| {title} | {arm} | {s['n']} | {s['chars_med']} | {s['nums_med']} | "
                      f"{s['top_opening_rate']:.1%} | {s['vocab_300']} |\n")

    for title, spec, gdir, kw in GROUPS:
        md.append(f"\n---\n\n## {title}\n")
        items = load_dataset(spec, kw["task"], seed=args.seed, limit=kw.get("limit"),
                             lookback=kw.get("lookback", 96), horizon=kw.get("horizon", 96),
                             max_windows=kw.get("max_windows"))
        by_id = {it.id: it for it in items}
        arms_caps = {a: load_caps(root, gdir, a) for a in ARMS}
        arms_caps = {a: c for a, c in arms_caps.items() if c}
        common = set.intersection(*(set(c) for c in arms_caps.values()))
        test_ids = sorted(i for i in common if "_te_" in i)[:args.n_per_dataset]

        for sid in test_ids:
            it = by_id[sid]
            tag = (f"true class = {it.label}" if it.label is not None
                   else "forecasting task (no class label)")
            md.append(f"\n### `{sid}`  ·  {tag}\n")
            md.append("\n**Ground truth (computed)**\n\n" + truth_block(it.series))
            if it.future is not None:
                fut = np.asarray(it.future, dtype=float)
                md.append(f"- the {len(fut)} future steps to forecast: "
                          + ", ".join(f"{v:.2f}" for v in fut) + "\n")
            md.append("\n")
            for arm in ARMS:
                if arm not in arms_caps:
                    continue
                cap = arms_caps[arm][sid].strip()
                md.append(f"\n**{ARM_LABEL[arm]}**  ({len(cap)} chars)\n\n")
                md.append("> " + cap.replace("\n", "\n> ") + "\n")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("".join(md), encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
